services:
  - type: web
    name: dev-ai-platform
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download fr_core_news_sm
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: API_KEY
        value: "ma_clé_secrète"